apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qevn-ingress
  namespace: qevn
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: api.qevn.workforce
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: qevn-gateway
                port:
                  number: 8000
          - path: /api/v1/stream
            pathType: Prefix
            backend:
              service:
                name: qevn-gateway
                port:
                  number: 8000
